sonar.projectKey=compare_ui
sonar.projectName=compare_ui
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=backend/app,frontend/src

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Ignore tests and output directories
sonar.exclusions=**/tests/**,output/**,frontend/node_modules/**,backend/venv/**,frontend/dist/**

# Fix Warnings
sonar.scm.disabled=true
sonar.python.version=3.10, 3.11
