#!/bin/bash
# Load Offline Images
# Run this script on the target air-gapped machine.

if [ ! -f "robot_verify_images.tar" ]; then
    echo "Error: robot_verify_images.tar not found in the current directory."
    echo "Please transfer the file generated by export_offline_images.sh to this location."
    exit 1
fi

echo "Loading images into local Docker daemon..."
docker load < robot_verify_images.tar

echo "Images loaded successfully!"
echo "You can now run 'docker compose up -d' using your .env configuration."
